### ISSUE TITLE
Cannot change user agent

### ISSUE THREAD

**Issue by abl** [tuanpmt/espduino#15]
Setting headers works well, but changing the user agent seems to have no effect.

I'm not sure if this is a bug with esp_bridge or just the particular version compiled and included here.

**Comment by tuanpmt** [comment]
i don't have fully tested for this, but with command ```setUserAgent("user agent")```, i've seen header modified in debug code

**Comment by abl** [comment]
Hmm. I'll test again with debug - I was using the release binary from this repo. (The debug binary doesn't work for me, but I'm using SoftwareSerial, so I'm really rate limited and lots of other things glitch out.)

**Comment by n8henrie** [comment]
I'm using debug code and also cannot set user agent; `rest.setUserAgent("my user agent")` right after setting headers in my code (which work), and I still get `User-Agent: ESPDRUINO@tuanpm`.

**Comment by n8henrie** [comment]
Think I got it: https://github.com/tuanpmt/espduino/pull/37
