### ISSUE TITLE
Can espduino Create a webserver ?

### ISSUE THREAD

**Issue by dogrocker** [tuanpmt/espduino#20]
Thanks @tuanpmt, for make this work well with esp8266 MQTT.

I'm looking to make softap when first connect to wifi uno. It will create a webserver to getting ssid, pass word and write to EEPROM on uno.

It look like now espduino only have an api for MQTT and clientTCP right?

If I want to do this thing I need to edit esp_bridge right?

Thanks.

**Comment by AkSuganthan** [comment]
I am also facing the same problem.

Pls help in this.
